### PR TITLE
fix(runtime-core) `SharedMemory.desc` is never used, remove it

### PR DESCRIPTION
**Pull request by Hywan**
This patch removes the `desc` field of `SharedMemory`. This field is
never used. Maybe it will be used in the future when the
implementations will be written, but so far, it only generates
warnings.

### CODE REVIEW

**Comment by bjfish** [comment]
Could we add a tag or something to allow it to be unused for now?

**Comment by Hywan** [comment]
Yup :-).

**Comment by xmclark** [comment]
bors try

**Pull request merged**
