### PR TITLE
Cranelift native

### PR DESCRIPTION
**Pull request by syrusakbary**
# Description

Get cranelift native working on Aarch64 (Darwin patch to come apart)

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by syrusakbary** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by syrusakbary** [comment]
Tests passed. Merging manually as this PR is actually enabling cranelift-native in more architectures.

**Comment by Hywan** [comment]
\o/

**Pull request merged**
