### PR TITLE
Fixed some memory leak issue with InstanceHandle

### PR DESCRIPTION
**Pull request by ptitSeb**
This is help with #3485 
This memory leak is also tracked there: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55183

### CODE REVIEW

**Review by syrusakbary — CHANGES_REQUESTED** [review]
Rename: `InstanceHandle` to `VMInstance` and `write_instance` to `into_vminstance`

**Comment by theduke** [comment]
I guess you are aware, but that rename is a breaking change and would require a major version bump for the vm crate.

**Comment by ptitSeb** [comment]
> I guess you are aware, but that rename is a breaking change and would require a major version bump for the vm crate.

I don't think `InstanceHandle` is only used Internaly. So we should be safe.

**Comment by theduke** [comment]
It's in the public API of `-vm`, so at least that create would need a bump.

**Comment by theduke** [comment]
It's also in the public api, because of `Artifact::instantiate()`.

**Comment by ptitSeb** [comment]
This also fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55183 when tested localy

**Review by syrusakbary — APPROVED** [review]
Looks good 👍

**Pull request merged**
