### PR TITLE
Readd and fixup changes from PR #2248

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Following up on #2248

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors ping

**Comment by MarkMcCaskey** [comment]
bors try-

**Comment by MarkMcCaskey** [comment]
bors try

**Review by Sifat1998 — APPROVED** [review]

**Comment by syrusakbary** [comment]
Tests failed because of temporary unavailability of aarch64 testing. Merging manually for now

**Pull request merged**
