### PR TITLE
Improved hashing algorithm

### PR DESCRIPTION
**Pull request by syrusakbary**
Based on this feedback:
https://twitter.com/jedisct1/status/1100200484764303361

# Speed analysis
meowhash encodes in 50ns (1Mb file).
blake2bp (SIMD version) encodes to about 500ns (1Mb file).
blake2 (non-SIMD version) encodes to about 1s (1Mb file).

### blake2
```
nginx HASH              time:   [1.0330 ms 1.0471 ms 1.0589 ms]
                        change: [-3.3836% -0.6012% +2.1520%] (p = 0.69 > 0.05)
```

### blake2bp
```
nginx HASH              time:   [510.72 us 526.18 us 541.60 us]
                        change: [-6.8755% -1.4050% +3.7167%] (p = 0.66 > 0.05)
```

### meowhash
```
nginx HASH              time:   [47.033 us 48.020 us 49.028 us]
                        change: [-95.542% -95.334% -95.097%] (p = 0.00 < 0.05)
```

## Other resources

Collision analysis: https://github.com/cmuratori/meow_hash/issues/7 (no collisions in a 156Gb dataset for 2M files, in the non-truncated version).

Hacker News article: https://news.ycombinator.com/item?id=18262627

### CODE REVIEW

**Comment by jedisct1** [comment]
You're using blake2, not blake2bp here. See https://docs.rs/blake2b_simd/0.4.1/blake2b_simd/blake2bp/index.html

**Comment by syrusakbary** [comment]
@jedisct1 thanks for the ping! I'll update the code and benchmark soon.

**Comment by syrusakbary** [comment]
After researching more we decided to merge this since the timings with blake2bp (500ns for a 1Mb file) are good enough for our use case.

Thanks @jedisct1 and @briansmith for bringing this to our attention.

**Comment by ephetic** [comment]
What is the difference in uniqueness guarantees?

**Pull request merged**
