### PR TITLE
fix(ci) Clean up Windows artifacts, installer, LLVM etc. #2112

### PR DESCRIPTION
**Pull request by Hywan**
(re-edit of https://github.com/wasmerio/wasmer/pull/2112)

# Description

1.  ~7ff16b4, First, we need to use our own LLVM built for Windows. This has been commited by error, see https://github.com/wasmerio/wasmer/pull/2008#discussion_r555588703.~ Our LLVM built aren't designed for mingw32. Let's keep LLVM from Choco for the moment.
2. 3946f3c, Second, we copy the `ATTRIBUTIONS` and `LICENSE` files twice. That's useless :-).
3. ~efff2c8 ,  Third, as discussed with @MarkMcCaskey, we want to rename `wasmer-windows.exe` to `wasmer-windows-installer.exe` for the sake of clarity.~ It will break the Wasmer installer, so let's keep that name as is.
4. 1a03e88, Fourth, let's create a `wasmer.tar.gz` archive for Windows.
5. 67e8679, Fiveth, let's upload the `wasmer.tar.gz` archive for Windows.
6. cf0c56c, Use `wasmer.zip` on Windows because it's difficult to untar+ungzip on this OS (as discused with @MarkMcCaskey).

# Review

- [ ] ~Add a short description of the the change to the CHANGELOG.md file~ not necessary

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Review by jubianchi — APPROVED** [review]

**Comment by Hywan** [comment]
```
/usr/bin/bash: zip: command not found
```

are you kidding me… :-@

**Pull request merged**
