### PR TITLE
Actually catch traps/panics/etc when using a typed func.

### PR DESCRIPTION
**Pull request by lachlansneff**
Some niche code in some of the other libraries will need to be added.

### CODE REVIEW

**Comment by lachlansneff** [comment]
Okay, let's give this a try.
bors try

**Comment by lachlansneff** [comment]
once more

bors try

**Comment by lachlansneff** [comment]
trying to fix windows build
bors try

**Comment by lachlansneff** [comment]
bors try

**Comment by lachlansneff** [comment]
pls
bors try

**Comment by bjfish** [comment]
It would be nice if there was more comments/documentation. For example, the `get_wasm_trampoline` could describe what is trampoline, where are they used, why are they're need. Or each of the traits/structs could describe their purpose.

**Comment by lachlansneff** [comment]
@bjfish Good idea, I'll do that before merging.

**Comment by lachlansneff** [comment]
*prays to the git gods*
bors r+

**Pull request merged**
