### PR TITLE
feat(c-api) Update cbindgen to 0.19

### PR DESCRIPTION
**Pull request by Hywan**
# Description

This patch updates cbindgen to 0.19.

# Review

- [ ] ~Add a short description of the change to the CHANGELOG.md file~ not necessary

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Comment by syrusakbary** [comment]
Assuming it was a flaky test. Re-doing:

bors try

**Comment by syrusakbary** [comment]
Noope, the error seem to be triggered by the last update

**Comment by syrusakbary** [comment]
Weird #2442 is also failing for the same reason, but it didn't touch any of this code. I suspect master might be failing for the same reason

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try-

**Review by syrusakbary — APPROVED** [review]

**Comment by Hywan** [comment]
Merging by hand because the patch touches a Github workflow file, and Bors refuses to run in this case :-).

**Pull request merged**
