### PR TITLE
Add packaging of headless wasmer to CI

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
# Review

- [x] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by syrusakbary** [comment]
I tried to run this locally and found some issues:
1. `make build-wasmer-headless-minimal` failed with xargo (I didn't have it installed)
2. `make build-wasmer-headless-minimal`  failed with:
```
     Running `rustc --crate-name std --edition=2018 /Users/syrus/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type dylib --crate-type rlib --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C embed-bitcode=no --cfg 'feature="panic_immediate_abort"' -C metadata=60028aaaca40da0a -C extra-filename=-60028aaaca40da0a --out-dir /var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps --target aarch64-apple-darwin -L dependency=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps -L dependency=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/release/deps --extern alloc=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/liballoc-07e8674f405c6b0b.rlib --extern cfg_if=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libcfg_if-70baff3d3723dab7.rlib --extern compiler_builtins=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libcompiler_builtins-1cdbc7a199f88376.rlib --extern core=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libcore-0a7ca6d120b757f8.rlib --extern hashbrown=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libhashbrown-0cbf105a7ba7c1f3.rlib --extern libc=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/liblibc-725a8917b1a3371e.rlib --extern panic_abort=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libpanic_abort-127ce52fd64bbd77.rlib --extern rustc_demangle=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/librustc_demangle-1fc7b2cde8b3add1.rlib --extern unwind=/var/folders/y7/9xrctzk562ncdztd0hm8xds00000gn/T/xargo.g8XughQ7yooe/target/aarch64-apple-darwin/release/deps/libunwind-81c49a6c8afde170.rlib --sysroot /Users/syrus/.xargo/HOST -Z force-unstable-if-unmarked --cfg backtrace_in_libstd`
error[E0463]: can't find crate for `panic_unwind`
```

The way I installed Xargo is at follows:

```bash
cargo install xargo
rustup default nightly  # xargo requires nightly
rustup component add rust-src  # required by xargo
```

I haven't been able to run this yet. Any extra things I need to do @MarkMcCaskey ?

**Comment by MarkMcCaskey** [comment]
@syrusakbary Yeah, so actually because of the `Xargo.toml` file, the "suggested" settings to add to the `Cargo.toml` aren't a suggestion anymore, they're a requirement... we may be able to use `RUSTFLAGS` to set `panic=abort` so that it'll at least work without the `Cargo.toml` modification... it wasn't possible to use `RUSTFLAGS` to set all the things we needed though

**Comment by MarkMcCaskey** [comment]
Unfortunately `xargo +nightly build` doesn't actually work, so nightly needs to be set manually

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Pull request merged**
