### PR TITLE
Prepare for 1.0.0-alpha4 release

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
# Review

- [x] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Review by nlewycky — APPROVED** [review]

**Comment by MarkMcCaskey** [comment]
I noticed https://github.com/wasmerio/wasmer-nightly/ got broken by the C API refactor, we need to fix that before we can release

**Comment by MarkMcCaskey** [comment]
Alright, that was really easy to fix

**Pull request merged**
