### PR TITLE
Implement bulk memory instructions

### LINKED ISSUE #2252: Does the LLVM Compiler Support bulk_memory?
### Summary

I'm using the llvm compiler along with the native engine, and bulk_memory instructions like `memory.copy` seem to cause panics.

### Additional details

It looks like certain wasm bulk memory operators, such as `MemoryCopy`, are not implemented by `compiler-llvm`. In cases when certain instructions are run (`memory.copy`, `memory.fill`, etc), the wasm execution will crash, hitting [this default case](https://github.com/wasmerio/wasmer/blob/master/lib/compiler-llvm/src/translator/code.rs#L9598-L9603).

My `wasmer` dependency in `Cargo.toml` looks like this:
```toml
wasmer = { version = "1.0.2", default-features = false, features = ["wat", "default-native", "default-llvm" ] }
```

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
resolves #2252 

Progress:
- [x] Cranelift (bulk.wast was failing in CI? need to investigate)
- [x] LLVM
- [x] Singlepass

# Review

- [x] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try-

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
Since all tests passed and the PR is approved I'll merge manually to skip more CI time

**Pull request merged**
