### PR TITLE
Continuous fuzzing

### PR DESCRIPTION
**Pull request by bookmoons**
Proposing to get continuous fuzzing running on Fuzzit, to provide some automated bug discovery. Integrates the nice existing fuzz target.

This integrates through Travis as shown in the Fuzzit docs. I see your main build system is Circle. If you'd rather do it through Circle I can look into it.

There's a [successful run](https://travis-ci.org/bookmoons/wasmer/builds/577214712) under my Travis account. If you'd like to try it you can set it up like this:
* Enable repo on [Travis](https://travis-ci.org/).
* In [Fuzzit](https://fuzzit.dev/) create the target `wasmer`.
* In Fuzzit settings grab an API key. In repo settings in Travis paste it to envvar `FUZZIT_API_KEY`.

### CODE REVIEW

**Comment by syrusakbary** [comment]
I love this!

We are working on moving to Azure pipelines #656, if you could integrate with it that would be awesome :)

**Comment by bookmoons** [comment]
Will get into that! Thanks for looking at it.

**Comment by syrusakbary** [comment]
Azure Pipelines has landed into master.
Now it should be easier to add the config there instead of using Travis 🤗

**Comment by bookmoons** [comment]
Nice. Will get into this soon.

**Comment by bookmoons** [comment]
I think this is reconfigured. A test build succeeds. Not sure if you can see this:
https://dev.azure.com/bookmoons/wasmer/_build/results?buildId=17

Fuzzit have kindly created wasmer org. I've preconfigured for an easier transition. If you [sign in](https://fuzzit.dev/) to create an account I can add you to the org.

Then setup is like this:
* In Fuzzit settings grab an API key.
* In Azure Pipelines, Edit the pipeline, open Variables, and paste the key to a FUZZIT_API_KEY variable. Make it secret to prevent exposure.

After that a build should work. I see a first fuzzing job in the queue already from my test build.

**Comment by bookmoons** [comment]
Brought this up to date:
* Rebased onto the latest.
* Upgraded to the latest Fuzzit client.
* I see there are some new fuzz targets (nice!). Integrated all targets with Fuzzit.

**Comment by syrusakbary** [comment]
Merging PR

**Comment by bookmoons** [comment]
Thanks for merging!

Is that build failure a problem? I can investigate if it shouldn't have happened.

**Comment by bookmoons** [comment]
Oh, maybe we haven't done the API key. If you'd like to [sign in](https://fuzzit.dev/) to Fuzzit to make an account I can add you to the org, then you'll have access to the keys.

**Comment by bookmoons** [comment]
Think I've added you to the org. I really should mention the step of switching orgs in the instructions. If you get into Fuzzit you should have a dropdown at the top where you can switch to the wasmer org, then you get into settings and pull an org API key.

**Comment by syrusakbary** [comment]
Closing this in favor of #843

**Pull request closed without merging**
