### PR TITLE
Update cranelift to 0.82

### PR DESCRIPTION
**Pull request by Amanieu**
This adds SIMD support on the Cranelift backend.

### CODE REVIEW

**Comment by syrusakbary** [comment]
Tests seem to be failing

**Comment by Amanieu** [comment]
The failure seems to be due to the wasmparser upgrade, I'm looking into it.

**Review by syrusakbary — APPROVED** [review]
We should be good to merge once the tests pass

**Comment by Amanieu** [comment]
It seems that the wasmparser upgrade may cause a breaking change in the C API. Specifically in this file: https://github.com/wasmerio/wasmer/blob/master/lib/c-api/src/wasm_c_api/unstable/parser/operator.rs

Is this an acceptable breaking change? The API is marked as unstable.

**Comment by Amanieu** [comment]
Nevermind I managed to not make it a breaking change.

**Comment by syrusakbary** [comment]
Tests passed, so I'm merging directly as I already reviewed it

**Pull request merged**
