### PR TITLE
Fix UB in setting memory in emscripten EmEnv

### LINKED ISSUE #2122: Undefined behavior in `EmEnv::set_memory`
### Describe the bug

`EmEnv::set_memory` is implemented as:

```rust
pub fn set_memory(&mut self, memory: Memory) {
        let ptr = Arc::as_ptr(&self.memory) as *mut _;
        unsafe {
            *ptr = Some(memory);
        }
    }
```

There are two problems with this code:
* casting `*const Memory` to `*mut Memory` creates a mutable pointer from an immutable pointer, which is UB.
* the `Arc` could have been cloned and sent to another thread, in which case writing to `ptr` is a data race.

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Fixes the UB and another issue caused by the reftypes PR merging in

Resolves #2122

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try-

**Review by syrusakbary — APPROVED** [review]

**Pull request merged**
