### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helje5**
Add link to SwiftyWasmer

# Description

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Review by Hywan — COMMENTED** [review]
Can you add a logo for Swift please? :-)

**Comment by helje5** [comment]
I used to use the one available on Wikipedia, but even they dropped it. Presumably because the Swift logo is an Apple trademark or something.

So I assume if Wikipedia isn't allowed a Swift logo, you probably aren't either ;-)

**Review by Hywan — APPROVED** [review]

**Comment by Hywan** [comment]
That's a valid assumption ;-p.

bors r+

**Comment by Hywan** [comment]
And thanks for the cool project!

**Pull request merged**
