### PR TITLE
Fix Singlepass issue #2347

### LINKED ISSUE #2159: singlepass crashes compiling fdiv + fcopysign
Testcase:

```
(module
  (func (export "_start") (result f64)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.div
    f64.copysign
  )
)
```

fails to build with singlepass:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lib/compiler-singlepass/src/codegen_x64.rs:513:60
```

the relevant part of the backtrace is:

```
   4: wasmer_compiler_singlepass::codegen_x64::FuncGen::emit_relaxed_binop
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:513:28
   5: wasmer_compiler_singlepass::codegen_x64::FuncGen::canonicalize_nan
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:341:9
   6: wasmer_compiler_singlepass::codegen_x64::FuncGen::feed_operator
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:3570:33
```

### LINKED ISSUE #2347: Panic in the singlepass compiler
```rust
fn main() {
    let jit = wasmer::JIT::new(wasmer::Singlepass::new());
    let store = wasmer::Store::new(&jit.engine());
    let bytes = vec![
        0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 124, 1, 127, 2, 1, 0, 3, 3, 2, 0, 0, 10, 20,
        2, 3, 0, 0, 11, 14, 0, 65, 255, 135, 140, 120, 183, 155, 155, 32, 0, 166, 0, 11,
    ];
    let _ = wasmer::Module::new(&store, bytes);
}
```

This results in 

```
thread 'tests::error_cases::test_simple_contract' panicked at 'called `Option::unwrap()` on a `None` value', /home/matklad/.cargo/git/checkouts/wasmer-0210ff4327f3d2ae/a98937b/lib/compiler-singlepass/src/codegen_x64.rs:513:60
```

wasmer "1.0.2"

### PR DESCRIPTION
**Pull request by chenyukang**
# Description
Fix Singlepass compiler issue: #2347 

I'm not sure whether the unit test case added to a suitable file. 
Any better suggestion?
@syrusakbary 

Edit by @Hywan: Close #2347, close #2159.

### CODE REVIEW

**Comment by chenyukang** [comment]
Issue #2159 is the same bug.

**Review by Hywan — COMMENTED** [review]
Looks good to me! Thanks!

I believe the best place to write those unit tests (the one your wrote, and the one from https://github.com/wasmerio/wasmer/issues/2159) is in `tests/wast/wasmer/`. Is it OK for you to do it?

Also please, do not forget to update the `CHANGELOG.md` file :-).

**Comment by chenyukang** [comment]
> Looks good to me! Thanks!
> 
> I believe the best place to write those unit tests (the one your wrote, and the one from #2159) is in `tests/wast/wasmer/`. Is it OK for you to do it?
> 
> Also please, do not forget to update the `CHANGELOG.md` file :-).

Ok, I will update it.

**Comment by chenyukang** [comment]
@Hywan Done!

**Review by Hywan — COMMENTED** [review]
Can you please rename the following files:

* `tests/wast/wasmer/nan-canonicalization-bug1.wast` to `tests/…/issue-2347.wast`
* ` tests/wast/wasmer/nan-canonicalization-bug2.wast` to `tests/…/issue-2159.wast`

please :-)?

And then we are good!

**Comment by chenyukang** [comment]
> Can you please rename the following files:
> 
> * `tests/wast/wasmer/nan-canonicalization-bug1.wast` to `tests/…/issue-2347.wast`
> * ` tests/wast/wasmer/nan-canonicalization-bug2.wast` to `tests/…/issue-2159.wast`
> 
> please :-)?
> 
> And then we are good!

No, we must keep the name with `nan-canonicalization`, because the logic here: 
https://github.com/wasmerio/wasmer/blob/master/tests/compilers/wast.rs#L19

This bug is only triggered when `try_nan_canonicalization` is true...

**Comment by syrusakbary** [comment]
Good catch @chenyukang!

Can we have then this names instead?
* `tests/wast/wasmer/nan-canonicalization-issue-2347`
* `tests/wast/wasmer/nan-canonicalization-issue-2159 `

Thanks!

**Comment by chenyukang** [comment]
> * tests/wast/wasmer/nan-canonicalization-issue-2159

Done！

**Review by Hywan — APPROVED** [review]
bors r+

**Pull request merged**
