### PR TITLE
Upgrade dynasm to 0.7.

### PR DESCRIPTION
**Pull request by losfair**
Fixes https://github.com/wasmerio/wasmer/issues/1488 .

### CODE REVIEW

**Comment by losfair** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by frol** [comment]
dynasm-rs 1.0 is released targeting stable Rust 1.45+ CensoredUsername/dynasm-rs#31 :tada:

**Comment by syrusakbary** [comment]
On the refactor project, we are already using latest dynasm in Rust stable :)

**Comment by frol** [comment]
Can the refactor project be compiled on stable Rust? Is there ETA or tracking issue on the refactor project?

**Comment by syrusakbary** [comment]
This PR is no longer needed as we are using latest dynasm compiling into Rust stable in latest Wasmer.

**Pull request closed without merging**
