### PR TITLE
Fix build error on some archs by using c_char instead of i8

### PR DESCRIPTION
**Pull request by silwol**
# Description

# Review

- [x] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by syrusakbary** [comment]
How do we know this works? Can we have a test for it?

**Comment by ptitSeb** [comment]
Is this because char are signed on x86 and unsigned on arm64?

**Comment by silwol** [comment]
> Is this because char are signed on x86 and unsigned on arm64?

Exactly. With this change, it uses the `c_char` directly, independently of the platform it builds on, and therefore inherits whatever type the alias points to.

**Review by ptitSeb — APPROVED** [review]

**Pull request merged**
