### PR TITLE
Remove usage of LZCNT and TZCNT from singlepass.

### PR DESCRIPTION
**Pull request by nlewycky**
# Description
This PR removes usage of LZCNT and TZCNT in singlepass to work on machines that don't support them. Unlike other instructions that fail loudly when not supported, LZCNT and TZCNT silently change behaviour by falling back to BSR and BSF which may produce different answers. They were used in the I32Clz, I32Ctz, I64Clz and I64Ctz instructions. Fixes i32.wast and i64.wast test failures on our Mac buildbot.

As an alternative, we could detect presence of LZCNT and TZCNT at runtime, either by running them directly or by querying CPUID to detect whether the CPU claims support for these instructions. I decided against that because having multiple paths is more complicated, and we aren't concerned with runtime of singlepass code, as a rule.

### CODE REVIEW

**Comment by nlewycky** [comment]
bors try

**Comment by nlewycky** [comment]
bors try-

**Comment by nlewycky** [comment]
bors try

**Comment by nlewycky** [comment]
bors try-

**Comment by nlewycky** [comment]
bors try

**Comment by nlewycky** [comment]
bors try

**Comment by Hywan** [comment]
I'm also a partisan of getting a single path rather than multiple paths. Thanks for the PR!

**Comment by nlewycky** [comment]
bors retry

**Pull request merged**
