### PR TITLE
Release 3.0.1

### PR DESCRIPTION
**Pull request by fschutt**
[bot] Release wasmer version 3.0.1

### CODE REVIEW

**Comment by syrusakbary** [comment]
Let's try to see if we can get #3355 also merged. But looks good

**Comment by fschutt** [comment]
[bot] Checks have passed. Publishing to crates.io...

**Comment by fschutt** [comment]
[bot] Successfully published wasmer version 3.0.1 to crates.io

**Comment by fschutt** [comment]
[bot] Checks have passed. Publishing to crates.io...

**Comment by fschutt** [comment]
[bot] Successfully published wasmer version 3.0.1 to crates.io

**Pull request merged**
