### PR TITLE
feat(interface-types) Implement the WAT decoder

### PR DESCRIPTION
**Pull request by Hywan**
WIP

The goal is the define a minimal WAT to AST decoder for WIT, so that it's muuuuuuch easier to develop and debug.

### CODE REVIEW

**Comment by Hywan** [comment]
Almost there! A public API is missing, and documentation of course.

**Comment by syrusakbary** [comment]
This reminded me of the WAT meme... 😂

WAT meme

**Comment by Hywan** [comment]
bors cancel

**Pull request merged**
