### PR TITLE
Port to FreeBSD

### PR DESCRIPTION
**Pull request by MikaelUrankar**
Port to FreeBSD

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]
This is awesome, thanks!
It would be great to generate also the binaries for FreeBSD in the GitHub Actions CI. We can do it in a PR apart though.

Great work!

**Comment by syrusakbary** [comment]
bors r +

**Comment by nlewycky** [comment]
Similarly, it'd be great to have a CI to make sure we can keep FreeBSD working!

**Pull request merged**
