### PR TITLE
fix file metadata wasi test

### LINKED ISSUE #453: Time going backwards???
### Describe the bug

```
thread 'main' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036:5
```

### Steps to reproduce
1. Unpack [rustc_binary.wasm.zip](https://github.com/wasmerio/wasmer/files/3193868/rustc_binary.wasm.zip).
2. ```
   wasmer run rustc_binary.wasm --backend singlepass --dir . --dir $(rustc --print sysroot)  -- example.rs --sysroot $(rustc --print sysroot) -Zcodegen-backend=metadata_only --target x86_64-unknown-linux-gnu
   ```

### Expected behavior

No panic.

### Actual behavior

Panic.

### Additional context

Using Rust + WASI.

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
gets the test working by properly filling in data into the stat

also resolves #453

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by bjorn3** [comment]
Thanks!

**Pull request merged**
