### PR TITLE
chore: Update Rust dependencies

### PR DESCRIPTION
**Pull request by Hywan**
# Description

This patch updates the Rust dependencies.

# Review

- [ ] ~Add a short description of the change to the CHANGELOG.md file~ not necessary

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
@Hywan you need to update `deny.toml` (you can test it locally with `cargo install cargo-deny` and then `cargo deny` on the wasmer root

**Comment by Hywan** [comment]
Nah, we have a conflict between 2 different versions of `object`. I'm fixing that.

**Comment by Hywan** [comment]
bors try

**Pull request merged**
