### PR TITLE
feat: Rename `wasmer-engine-native` to `wasmer-engine-dylib`

### PR DESCRIPTION
**Pull request by Hywan**
This (small) patch renames the `wasmer-engine-native` crate into
`wasmer-engine-dylib`. We believe the new name conveys
better the intent of the engine.

I will update the `CHANGELOG` later.

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
The error comes from the `compiler_test` proc macro that transforms the engine name (`SharedObject`) into the feature name (`sharedobject`), but in this case, it's wrong (it must be `shared-object`). I'm modifying the code accordingly.

**Comment by Hywan** [comment]
bors try

**Comment by syrusakbary** [comment]
As talked offline, let's go with `wasmer-engine-dylib`. Apologizes for the misdirection here!

**Review by secret223 — APPROVED** [review]

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Review by jubianchi — APPROVED** [review]

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Pull request merged**
