### PR TITLE
Add a cargo-deny list.

### PR DESCRIPTION
**Pull request by nlewycky**
# Description
I recommend reading each of the individual commits in this PR. They start off by adding the original template, modifying that template so that it's as strict as possible but still passes (mostly loosening requirements), then modifying Wasmer where it was easy to do so in order to tighten the requirements.

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Review by syrusakbary — COMMENTED** [review]
Let's also add a check in the CI (so we check cargo deny as part of future PRs)

**Comment by nlewycky** [comment]
> Let's also add a check in the CI (so we check cargo deny as part of future PRs)

Yep! I was planning to do that in a separate PR. Should I add it in this one?

**Pull request merged**
