### PR TITLE
Check for unused excluded spectest failures.

### PR DESCRIPTION
**Pull request by losfair**
Previously if a spectest failure was (maybe unintentionally) fixed then the corresponding line in `excludes.txt` will be silently ignored. This PR adds a check that each excluded spectest failure actually occurred.

### CODE REVIEW

**Comment by losfair** [comment]
bors try

**Comment by losfair** [comment]
bors try

**Comment by losfair** [comment]
bors try

**Comment by syrusakbary** [comment]
(merged without bors as `bors try` succeeded)

**Pull request merged**
