### PR TITLE
Add feature matrix document

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
[rendered](https://github.com/wasmerio/wasmer/blob/docs/add-feature-matrix/docs/feature_matrix.md)

# Review

- [x] Create a short description of the the change in the CHANGELOG.md file

### CODE REVIEW

**Comment by torch2424** [comment]
@syrusakbary 

> This is a good first PR. Perhaps we can use emojis (✅| ✔️, ❌) instead of (Yes, No)

Hmmm. Do you happen to know how these are read for accessibility? 🤔 

But if they are read in a way that makes sense, I think it is a great idea! 😄

**Comment by syrusakbary** [comment]
> Hmmm. Do you happen to know how these are read for accessibility? 🤔

No idea

**Comment by MarkMcCaskey** [comment]
I checked and the osx screen reader can handle emoji reasonably well

**Comment by torch2424** [comment]
@MarkMcCaskey Thanks for checking Mark! 😄

**Pull request merged**
