### PR TITLE
test: Test the JIT engine being dropped twice through the Store

### PR DESCRIPTION
**Pull request by Hywan**
I think we have a bug in the `engine-jit` where the `UnwindRegistry` on Linux (Ubuntu) fails when dropped twice.

This PR adds a test to check that.

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors cancel

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by Hywan** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by sebpuetz** [comment]
Just wondering if you saw #1568: The `UnwindRegistry` is **not** dropped twice. A `Vec<u8>` owned by `CodeMemory` inside the `Store` containing the empty frame gets dropped before deregistering the frames. This `Vec`'s buffer then gets overwritten and the orginally 0-length entry gets changed to some nonsense which causes the abort.

**Comment by Hywan** [comment]
Yup, this PR was just a test!

**Pull request closed without merging**
