### PR TITLE
Remove type_to_llvm_int_only, only use type_to_llvm.

### PR DESCRIPTION
**Pull request by nlewycky**

### CODE REVIEW

**Comment by syrusakbary** [comment]
Nice refactor

**Comment by nlewycky** [comment]
Travis CI says:
> $ rustup update
> info: no updatable toolchains installed
> info: checking for self-updates
> error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateVo1oOK/release-stable.toml'
> error: caused by: failed to make network request
> error: caused by: https://static.rust-lang.org/rustup/release-stable.toml: error trying to connect: failed to lookup address information: Temporary failure in name resolution
> error: caused by: failed to lookup address information: Temporary failure in name resolution
> The command "rustup update" failed and exited with 1 during .

**Pull request merged**
