### PR TITLE
Update memoffset to 0.9.0

### PR DESCRIPTION
**Pull request by joshlf**
Implemented as part of https://github.com/rust-lang/rust/issues/111839

# Description

### CODE REVIEW

**Comment by joshlf** [comment]
> There's lockfiles that need to be udpated

Ooops, thanks! Ran `cargo update`.

**Comment by joshlf** [comment]
Any advice on what to do about this failure in [this job](https://github.com/wasmerio/wasmer/actions/runs/6616000302/job/17969389461?pr=4273)?

```text
---- test_imported_function_env stdout ----
Error: Error { kind: Wast(Error { inner: ErrorInner { text: Some(Text { line: 10, col: 9, snippet: "        (set_local $x (i32.sub (get_local $x) (i32.const 1)))" }), file: None, span: Span { offset: 356 }, kind: Custom("unknown operator or unexpected token") } }) }
```

Same with this failure in [this job](https://github.com/wasmerio/wasmer/actions/runs/6616000302/job/17969380885?pr=4273):

```text
---- metering::complex_loop::cranelift::universal stdout ----
thread 'metering::complex_loop::cranelift::universal' panicked at 'called `Result::unwrap()` on an `Err` value: Wasm(Generic("Error when converting wat: unknown operator or unexpected token\n     --> <anon>:9:13\n      |\n    9 |             set_local $l0\n      |             ^"))', tests/compilers/metering.rs:159:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: compilers::metering::complex_loop::complex_loop
   4: compilers::metering::complex_loop::cranelift::universal
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- metering::complex_loop::llvm::universal stdout ----
thread 'metering::complex_loop::llvm::universal' panicked at 'called `Result::unwrap()` on an `Err` value: Wasm(Generic("Error when converting wat: unknown operator or unexpected token\n     --> <anon>:9:13\n      |\n    9 |             set_local $l0\n      |             ^"))', tests/compilers/metering.rs:159:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: compilers::metering::complex_loop::complex_loop
   4: compilers::metering::complex_loop::llvm::universal
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- metering::complex_loop::singlepass::universal stdout ----
thread 'metering::complex_loop::singlepass::universal' panicked at 'called `Result::unwrap()` on an `Err` value: Wasm(Generic("Error when converting wat: unknown operator or unexpected token\n     --> <anon>:9:13\n      |\n    9 |             set_local $l0\n      |             ^"))', tests/compilers/metering.rs:159:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: compilers::metering::complex_loop::complex_loop
   4: compilers::metering::complex_loop::singlepass::universal
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
```

**Comment by syrusakbary** [comment]
The errors seem unrelated to the PR. Not sure why they are failing exactly. Rerunning the tests again

**Comment by theduke** [comment]
I pushed a commit lifting memoffset into a workspace dependency to avoid duplication.

**Review by theduke — APPROVED** [review]

**Pull request merged**
