### PR TITLE
add notes for llvm

### PR DESCRIPTION
**Pull request by chenyukang**
# Description
Add details for LLVM dependency.

close issue #2435

### CODE REVIEW

**Comment by chenyukang** [comment]
Is there any better way to pass a parameter for "bash -c“ ?

**Comment by Hywan** [comment]
I don't know :-).

**Comment by chenyukang** [comment]
https://apt.llvm.org/llvm.sh will prepare everything ok for LLVM, 
I didn't know it, since I only reading the official document website, 
so it's better add this PR:
https://github.com/wasmerio/docs.wasmer.io/pull/129/files

**Comment by syrusakbary** [comment]
I'll merge manually after #2457 is merged

**Pull request merged**
