### PR TITLE
Fix sockets

### PR DESCRIPTION
**Pull request by Arshia001**
A couple of small fixes to sockets:

* Fixed endianness issue when deserializing IPv6 addresses that caused swapped bytes in each `u16`.
* Fixed receiving data from UDP sockets that have not been connected to a remote socket (i.e. server sockets).

### CODE REVIEW

**Comment by ptitSeb** [comment]
This seems very similar to https://github.com/wasmerio/wasmer/pull/4166

**Comment by Arshia001** [comment]
@theduke the problem is that UDP is still not really working. There's something wrong with either binding or receiving, but I haven't figured out exactly what it is yet.

**Comment by theduke** [comment]
> @theduke the problem is that UDP is still not really working. There's something wrong with either binding or receiving, but I haven't figured out exactly what it is yet.

Even more important to have a test then.

**Comment by Arshia001** [comment]
Absolutely, as soon as someone actually fixes it. I'm out of time for now, have to move on to other priorities, but I'll keep this on my task list for later.

**Comment by Arshia001** [comment]
@theduke CI should be green soon, just need an approval to get this merged in

**Review by theduke — APPROVED** [review]

**Pull request merged**
