### PR TITLE
chore: Update `wast`

### PR DESCRIPTION
**Pull request by Hywan**
# Description

Closes https://github.com/wasmerio/wasmer/pull/1816.
This PR updates `wast` to its latest version.

# Review

- ~[ ] Add a short description of the the change to the CHANGELOG.md file~ not necessary I guess

### CODE REVIEW

**Comment by Hywan** [comment]
bors try

**Review by syrusakbary — APPROVED** [review]

**Comment by jubianchi** [comment]
Just updated @Hywan's commit because, starting from `25.0` `wast` creates failures in our test suite.

LGTM and continue investigations in another issue/PR.

**Pull request merged**
