### PR TITLE
Update rkyv 0.7.40 and prettytable-rs to 0.10.0

### LINKED ISSUE #3576: Tracking issue oss-fuzz #55730
OSS-Fuzz project found an issue with Wasmer.

tracking is here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55730

Reproduced localy, using reproducing guide https://google.github.io/oss-fuzz/advanced-topics/reproducing/ with local sources.
`python3 infra/helper.py reproduce wasmer deterministic ~/clusterfuzz-testcase-minimized-deterministic-5042720751353856`
```
INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e HELPER=True -e ARCHITECTURE=x86_64 -v /home/seb/git/oss-fuzz/build/out/wasmer:/out -v /home/seb/clusterfuzz-testcase-minimized-deterministic-5042720751353856:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce deterministic -runs=100.
+ FUZZER=deterministic
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer deterministic -runs=100 /testcase
/out/deterministic -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase -detect_leaks=0 < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2525592623
INFO: Loaded 1 modules   (1791733 inline 8-bit counters): 1791733 [0x55dbcb448050, 0x55dbcb5fd745),
INFO: Loaded 1 PC tables (1791733 PCs): 1791733 [0x55dbcb5fd748,0x55dbcd154698),
/out/deterministic: Running 1 inputs 100 time(s) each.
Running: /testcase
=================================================================
==17==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000065100 at pc 0x55dbc7cc94b9 bp 0x7ffcae1f21f0 sp 0x7ffcae1f21e8
WRITE of size 1 at 0x621000065100 thread T0
SCARINESS: 31 (1-byte-write-heap-buffer-overflow)
    #0 0x55dbc7cc94b8 in core::ptr::write::h8c79a2887f552e25 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/core/src/ptr/mod.rs:1354:9
    #1 0x55dbc7cc94b8 in core::ptr::mut_ptr::_$LT$impl$u20$$BP$mut$u20$T$GT$::write::haefcbf644b69caf4 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/core/src/ptr/mut_ptr.rs:1469:18
    #2 0x55dbc7cc94b8 in wasmer_types::table::_::_$LT$impl$u20$rkyv..Archive$u20$for$u20$wasmer_types..table..TableStyle$GT$::resolve::h650365549de728da /src/wasmer/lib/types/src/table.rs:6:77
    #3 0x55dbc7cc94b8 in _$LT$rkyv..ser..serializers..alloc..AlignedSerializer$LT$A$GT$$u20$as$u20$rkyv..ser..Serializer$GT$::resolve_aligned::h6b31d3e7070733dd /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/serializers/alloc.rs:84:9
    #4 0x55dbc7cc94b8 in _$LT$rkyv..ser..serializers..CompositeSerializer$LT$S$C$C$C$H$GT$$u20$as$u20$rkyv..ser..Serializer$GT$::resolve_aligned::h26dd04261864f3c0 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/serializers/mod.rs:161:9
    #5 0x55dbc7cc94b8 in rkyv::impls::core::_$LT$impl$u20$rkyv..SerializeUnsized$LT$S$GT$$u20$for$u20$$u5b$T$u5d$$GT$::serialize_unsized::hae00f17f6c8618b9 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/core/mod.rs:216:21
    #6 0x55dbc7e4272c in rkyv::vec::ArchivedVec$LT$T$GT$::serialize_from_slice::h7a64a33262dbb614 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/vec/mod.rs:116:18
    #7 0x55dbc7e4272c in rkyv::impls::alloc::vec::_$LT$impl$u20$rkyv..Serialize$LT$S$GT$$u20$for$u20$alloc..vec..Vec$LT$T$GT$$GT$::serialize::h2d18e0169222de00 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/alloc/vec.rs:53:9
    #8 0x55dbc7e4272c in wasmer_types::entity::primary_map::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..entity..primary_map..PrimaryMap$LT$K$C$V$GT$$GT$::serialize::hace0689aa7483027 /src/wasmer/lib/types/src/entity/primary_map.rs:36:10
    #9 0x55dbc7e4272c in wasmer_types::compilation::module::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..compilation..module..CompileModuleInfo$GT$::serialize::h36a9f9eeec680dbd /src/wasmer/lib/types/src/compilation/module.rs:14:39
    #10 0x55dbc7c9d32b in wasmer_types::serialize::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..serialize..SerializableModule$GT$::serialize::hed1ed09d6544ba74 /src/wasmer/lib/types/src/serialize.rs:53:36
    #11 0x55dbc7c9d32b in rkyv::ser::Serializer::serialize_value::hd1a8bfbe9d68d9dc /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/mod.rs:78:24
    #12 0x55dbc7e00ae7 in wasmer_types::serialize::SerializableModule::serialize::hebf181960f73e0c0 /src/wasmer/lib/types/src/serialize.rs:76:19
    #13 0x55dbc74a529e in _$LT$wasmer_compiler..artifact_builders..artifact_builder..ArtifactBuild$u20$as$u20$wasmer_compiler..traits..ArtifactCreate$GT$::serialize::hc3071c1c711fde6c /src/wasmer/lib/compiler/src/artifact_builders/artifact_builder.rs:223:31
    #14 0x55dbc7485d98 in _$LT$wasmer_compiler..engine..artifact..Artifact$u20$as$u20$wasmer_compiler..traits..ArtifactCreate$GT$::serialize::hf77aef766cc4137f /src/wasmer/lib/compiler/src/engine/artifact.rs:265:9
    #15 0x55dbc5056d09 in wasmer::sys::module::Module::serialize::h0550de4fbff6cc27 /src/wasmer/lib/api/src/sys/module.rs:222:9
    #16 0x55dbc0f99dc0 in deterministic::compile_and_compare::h3187c52e242263cd /src/wasmer/fuzz/fuzz_targets/deterministic.rs:30:17
    #17 0x55dbc0f9da29 in deterministic::_::run::hd546a20ad3ea4a5a /src/wasmer/fuzz/fuzz_targets/deterministic.rs:63:5
    #18 0x55dbc0f9bde6 in rust_fuzzer_test_input /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:297:60
    #19 0x55dbc82d9c3f in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::hcfe9a25825b5102f /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:61:9
    #20 0x55dbc82d9c3f in std::panicking::try::do_call::h551b686bc76a513c /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panicking.rs:483:40
    #21 0x55dbc82deb87 in __rust_try libfuzzer_sys.8ddae39d-cgu.0
    #22 0x55dbc82ddde5 in std::panicking::try::hffb1a5d577c78059 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panicking.rs:447:19
    #23 0x55dbc82ddde5 in std::panic::catch_unwind::hb3197a9f7e35a2c9 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panic.rs:140:14
    #24 0x55dbc82ddde5 in LLVMFuzzerTestOneInput /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:59:22
    #25 0x55dbc82fd1d3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #26 0x55dbc82e8932 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #27 0x55dbc82ee1dc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #28 0x55dbc8317712 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #29 0x7fc39e300082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #30 0x55dbc0c3e7bd in _start (/out/deterministic+0x34437bd) (BuildId: 530c5b64312fa21c5f7383ac6760bac046c80ec1)

DEDUP_TOKEN: core::ptr::write::h8c79a2887f552e25--core::ptr::mut_ptr::_$LT$impl$u20$$BP$mut$u20$T$GT$::write::haefcbf644b69caf4--wasmer_types::table::_::_$LT$impl$u20$rkyv..Archive$u20$for$u20$wasmer_types..table..TableStyle$GT$::resolve::h650365549de728da
0x621000065100 is located 0 bytes to the right of 4096-byte region [0x621000064100,0x621000065100)
allocated by thread T0 here:
    #0 0x55dbc0cc21f6 in __interceptor_realloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:85:3
    #1 0x55dbc7cc7ab0 in alloc::alloc::realloc::hf0a092c6887bc94c /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/alloc/src/alloc.rs:132:14
    #2 0x55dbc7cc7ab0 in rkyv::util::aligned_vec::AlignedVec::reserve::h5e838d3d0a06a607 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/util/aligned_vec.rs:308:40
    #3 0x55dbc7cc7ab0 in _$LT$rkyv..ser..serializers..alloc..AlignedSerializer$LT$A$GT$$u20$as$u20$rkyv..ser..Serializer$GT$::resolve_aligned::h66852c0290f059c9 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/serializers/alloc.rs:79:9
    #4 0x55dbc7cc7ab0 in _$LT$rkyv..ser..serializers..CompositeSerializer$LT$S$C$C$C$H$GT$$u20$as$u20$rkyv..ser..Serializer$GT$::resolve_aligned::h5730063fa4f566d7 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/serializers/mod.rs:161:9
    #5 0x55dbc7cc7ab0 in rkyv::impls::core::_$LT$impl$u20$rkyv..SerializeUnsized$LT$S$GT$$u20$for$u20$$u5b$T$u5d$$GT$::serialize_unsized::h9cc21075232ac348 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/core/mod.rs:216:21
    #6 0x55dbc7cd2326 in rkyv::vec::ArchivedVec$LT$T$GT$::serialize_from_slice::hc66ae20dd23797ea /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/vec/mod.rs:116:18
    #7 0x55dbc7cd2326 in rkyv::impls::alloc::vec::_$LT$impl$u20$rkyv..Serialize$LT$S$GT$$u20$for$u20$alloc..vec..Vec$LT$T$GT$$GT$::serialize::hb0511dbaf1314885 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/alloc/vec.rs:53:9
    #8 0x55dbc7cd2326 in wasmer_types::compilation::section::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..compilation..section..SectionBody$GT$::serialize::h2b1cfdbda08e80b9 /src/wasmer/lib/types/src/compilation/section.rs:74:10
    #9 0x55dbc7cd2326 in wasmer_types::compilation::section::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..compilation..section..CustomSection$GT$::serialize::h55d08625de4512eb /src/wasmer/lib/types/src/compilation/section.rs:55:10
    #10 0x55dbc7cd2326 in rkyv::impls::core::_$LT$impl$u20$rkyv..SerializeUnsized$LT$S$GT$$u20$for$u20$$u5b$T$u5d$$GT$::serialize_unsized::hf51f527f9a15c7f5 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/core/mod.rs:212:36
    #11 0x55dbc7e85d9d in rkyv::vec::ArchivedVec$LT$T$GT$::serialize_from_slice::h58607297703973c5 /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/vec/mod.rs:116:18
    #12 0x55dbc7e85d9d in rkyv::impls::alloc::vec::_$LT$impl$u20$rkyv..Serialize$LT$S$GT$$u20$for$u20$alloc..vec..Vec$LT$T$GT$$GT$::serialize::h8242fbe5c6ca416f /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/impls/alloc/vec.rs:53:9
    #13 0x55dbc7e85d9d in wasmer_types::entity::primary_map::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..entity..primary_map..PrimaryMap$LT$K$C$V$GT$$GT$::serialize::hb3903d20c9577c17 /src/wasmer/lib/types/src/entity/primary_map.rs:36:10
    #14 0x55dbc7e85d9d in wasmer_types::serialize::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..serialize..SerializableCompilation$GT$::serialize::hee5b9a704f2ba6d3 /src/wasmer/lib/types/src/serialize.rs:19:45
    #15 0x55dbc7c9d114 in wasmer_types::serialize::_::_$LT$impl$u20$rkyv..Serialize$LT$__S$GT$$u20$for$u20$wasmer_types..serialize..SerializableModule$GT$::serialize::hed1ed09d6544ba74 /src/wasmer/lib/types/src/serialize.rs:53:36
    #16 0x55dbc7c9d114 in rkyv::ser::Serializer::serialize_value::hd1a8bfbe9d68d9dc /rust/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.39/src/ser/mod.rs:78:24
    #17 0x55dbc7e00ae7 in wasmer_types::serialize::SerializableModule::serialize::hebf181960f73e0c0 /src/wasmer/lib/types/src/serialize.rs:76:19
    #18 0x55dbc74a529e in _$LT$wasmer_compiler..artifact_builders..artifact_builder..ArtifactBuild$u20$as$u20$wasmer_compiler..traits..ArtifactCreate$GT$::serialize::hc3071c1c711fde6c /src/wasmer/lib/compiler/src/artifact_builders/artifact_builder.rs:223:31
    #19 0x55dbc7485d98 in _$LT$wasmer_compiler..engine..artifact..Artifact$u20$as$u20$wasmer_compiler..traits..ArtifactCreate$GT$::serialize::hf77aef766cc4137f /src/wasmer/lib/compiler/src/engine/artifact.rs:265:9
    #20 0x55dbc5056d09 in wasmer::sys::module::Module::serialize::h0550de4fbff6cc27 /src/wasmer/lib/api/src/sys/module.rs:222:9
    #21 0x55dbc0f99dc0 in deterministic::compile_and_compare::h3187c52e242263cd /src/wasmer/fuzz/fuzz_targets/deterministic.rs:30:17
    #22 0x55dbc0f9da29 in deterministic::_::run::hd546a20ad3ea4a5a /src/wasmer/fuzz/fuzz_targets/deterministic.rs:63:5
    #23 0x55dbc0f9bde6 in rust_fuzzer_test_input /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:297:60
    #24 0x55dbc82d9c3f in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::hcfe9a25825b5102f /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:61:9
    #25 0x55dbc82d9c3f in std::panicking::try::do_call::h551b686bc76a513c /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panicking.rs:483:40
    #26 0x55dbc82deb87 in __rust_try libfuzzer_sys.8ddae39d-cgu.0
    #27 0x55dbc82ddde5 in std::panicking::try::hffb1a5d577c78059 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panicking.rs:447:19
    #28 0x55dbc82ddde5 in std::panic::catch_unwind::hb3197a9f7e35a2c9 /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panic.rs:140:14
    #29 0x55dbc82ddde5 in LLVMFuzzerTestOneInput /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.5/src/lib.rs:59:22
    #30 0x55dbc82fd1d3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #31 0x55dbc82e8932 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #32 0x55dbc82ee1dc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #33 0x55dbc8317712 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #34 0x7fc39e300082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __interceptor_realloc--alloc::alloc::realloc::hf0a092c6887bc94c--rkyv::util::aligned_vec::AlignedVec::reserve::h5e838d3d0a06a607
SUMMARY: AddressSanitizer: heap-buffer-overflow /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/core/src/ptr/mod.rs:1354:9 in core::ptr::write::h8c79a2887f552e25
Shadow bytes around the buggy address:
  0x0c42800049d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800049e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42800049f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280004a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280004a10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4280004a20:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280004a30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280004a40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280004a50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280004a60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280004a70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17==ABORTING
```

### PR DESCRIPTION
**Pull request by ptitSeb**
Update of some craye dependancies:

rkyv to 0.7.40 (but this doesn't fix #3576 )
prettytable-rs to 0.10.0 (github security warning about the old version used, moderate severity)

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
Approved, although I think we already talked bumping rkyv would require a bumped magic version since the serialized data would be a bit improved

**Comment by ptitSeb** [comment]
We did talk about that, but since the update didn't fixed the fuzz issue, I have not bumped the magic. I still can do it.

**Comment by syrusakbary** [comment]
I'm happy either way, just wanted to make sure we are doing a intentional decision there

**Comment by ptitSeb** [comment]
Increasing MAGIC is not without consequences, so I prefer to do it only when needed or really beneficial.

**Pull request merged**
