### PR TITLE
Feature/wasi cross platform skeleton

### PR DESCRIPTION
**Pull request by MarkMcCaskey**

### CODE REVIEW

**Comment by lachlansneff** [comment]
I'd prefer to still have the main function implementations in a single location and they can call out to the platform-specific implementation.

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try-

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Pull request merged**
