### PR TITLE
Upgrade graphql-ws-client to v0.8.0

### PR DESCRIPTION
**Pull request by obmarg**
Hello wasmer people.

I'm the author of `graphql-ws-client`, the library you're using to do GraphQL subscriptions.  I've put a bunch of effort into simplifying and improving its API lately.  I updated your use of it in this repo as part of my testing effort, so figured I might as well share that update and save you some work - so here it is.

### CODE REVIEW

**Comment by theduke** [comment]
@obmarg thanks for the PR.

Do you mind upgrading (tokio-)tungstenite in the other crates as well so we have a single version across the workspace?

**Comment by theduke** [comment]
@obmarg also note: the failing test is flaky, not caused by your PR.

**Comment by obmarg** [comment]
@theduke done.

**Comment by theduke** [comment]
We have since upgraded to `0.11`.

**Pull request closed without merging**
