### PR TITLE
Added API compatibility layer

### PR DESCRIPTION
**Pull request by syrusakbary**
# Description

Added API compatibility layer.
This PR supersedes #2358

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by syrusakbary** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try-

**Comment by syrusakbary** [comment]
bors try

**Review by jubianchi — APPROVED** [review]

**Pull request merged**
