### PR TITLE
use rkyv deserialize to replace bincode on jit artifact

### PR DESCRIPTION
**Pull request by ailisp**
# Description

So this is applying similar technique to accelerate deserialize an jit artifact. I test by adding this in tests/compiler/serialize.rs, fn test_deserialize:
```
    let wat = std::fs::read("lib/c-api/tests/assets/qjs.wasm").unwrap();

    let module = Module::new(&store, wat)?;
    let serialized_bytes = module.serialize()?;

    let headless_store = get_headless_store();

    let start = std::time::Instant::now();
    let deserialized_module = unsafe { Module::deserialize(&headless_store, &serialized_bytes)? };
    println!("deserialize takes {:?}", start.elapsed());
```
run it with 
```
cargo test --features singlepass,test-singlepass,test-jit --test compilers serialize::test_deserialize --release -- --nocapture
```
Before it was 11-12ms, this PR make it 6-9ms, most of the time around 7ms. The optimization is visible, but we may achieve a faster one via Archive, that is replace all usage of SerializableModule and its fields, to ArchivedSerializableModule - this would make deserialize an O(1) mmap operation, but also add further intrusive changes based on this PR.
 
# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by syrusakbary** [comment]
Hey @ailisp I've created actually a very similar PR yesterday #2250.
There is a bug on rkyv that I'm trying to debug with it's creator (as it only triggers in rkyv 0.6.0)

**Comment by ailisp** [comment]
@syrusakbary Ah I'll close this in favor of your PR. i actually checked yesterday but happened to before your PR isn't happen and then start work :joy:, let me know if i can help on review or the rkyv bug (maybe)

**Comment by syrusakbary** [comment]
If you want to reproduce the bug, you need to:
* just follow the instructions in the PR. It works properly with rkyv 0.4.3
* Revert this commit https://github.com/wasmerio/wasmer/pull/2250/commits/4c54d863ce0a3edd319a962ac69bdd8877867753
* Run again the command: `./target/release/wasmer run lib/c-api/tests/assets/qjs.wasm --disable-cache -- -h`

**Comment by djkoloski** [comment]
The bug in question has been fixed as of 0.6.1. rkyv issue: https://github.com/djkoloski/rkyv/issues/116

**Pull request closed without merging**
