### PR TITLE
Re-enable llvm build in appveyor

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by xmclark** [comment]
bors try

**Comment by xmclark** [comment]
bors try

**Comment by syrusakbary** [comment]
It looks good! To prove that is working we will need also to:
* Let cargo compile llvm backend on windows (reverting https://github.com/wasmerio/wasmer/pull/239/commits/3a4325c5a3c6df990797f1d40c54609bcd832a25)
* Modify the appveyor config to test also llvm-backend https://github.com/wasmerio/wasmer/blob/master/.appveyor.yml#L53

**Comment by bjfish** [comment]
bors try

**Comment by bjfish** [comment]
bors try

**Comment by bjfish** [comment]
bors retry

**Comment by bjfish** [comment]
bors try

**Comment by bjfish** [comment]
bors try

**Comment by bjfish** [comment]
Going to close this for now as this is stale and not actively worked on, it may be a good reference in the future.

**Pull request closed without merging**
