### PR TITLE
add a compiler test to check for deterministic

### PR DESCRIPTION
**Pull request by xofyarg**
This is to test #2173, the empty test always pass while the table one
fails sometimes.

# Description

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
Thanks for writing up a test for us for this!

Nick probably has more context than me on this, so he should probably be the point of contact for this. But tests that only sometimes fail are pretty high risk in that we can break it and theoretically never find out, given sufficiently bad luck. That said, I think it may be useful for testing locally to see if things are fixed.

**Comment by xofyarg** [comment]
> tests that only sometimes fail are pretty high risk in that we can break it and theoretically never find out

I agree. The binary compiled from our production code changes every time, but it's unpractical to add it here. I think if the root cause can be found, I can improve the test later.

It's still failing on current master. @nlewycky when you have capacity, let me know how I can help with this, thank you.

**Comment by nlewycky** [comment]
Could you please add a fuzzer for this? Over the past two days I've updated the existing fuzz tests in wasmer so that we could use it to find more cases of non-determinism. You can start with fuzz/fuzz_targets/jit_cranelift.rs, replace the implementation of `fuzz_target!`... with `let wasm_bytes = module.to_bytes();` followed by your test's `compile_and_compare(&wasm_bytes)` function, also update fuzz/Cargo.toml. Run it with `cargo fuzz run fuzzername`.

**Comment by xofyarg** [comment]
I added a commit for fuzz with jit_cranelift engine. When trying to enable other compiler/engine combinations, cargo fuzz complained about memory leak:

```
    Finished release [optimized] target(s) in 0.06s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/deterministic -artifact_prefix=/home/user/wasmer/fuzz/artifacts/deterministic/ /home/user/wasmer/fuzz/corpus/deterministic`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2915527380
INFO: Loaded 1 modules   (603155 inline 8-bit counters): 603155 [0x559fbedb2eba, 0x559fbee462cd),
INFO: Loaded 1 PC tables (603155 PCs): 603155 [0x559fbee462d0,0x559fbf77a400),
INFO:      212 files found in /home/user/wasmer/fuzz/corpus/deterministic
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 212 min: 1b max: 8b total: 989b rss: 95Mb
/home/user/llvm-11.0.1/bin/llvm-symbolizer: /lib64/libtinfo.so.6: no version information available (required by /home/user/llvm-11.0.1/bin/llvm-symbolizer)

=================================================================
==2144472==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 4 object(s) allocated from:
    #0 0x559fb5f07584 in strdup /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:437:3
    #1 0x559fb8b66926 in LLVMVerifyModule (/home/user/wasmer/fuzz/target/x86_64-unknown-linux-gnu/release/deterministic+0x4792926)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 4 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x7d,
}
artifact_prefix='/home/user/wasmer/fuzz/artifacts/deterministic/'; Test unit written to /home/user/wasmer/fuzz/artifacts/deterministic/leak-c2b7df6201fdd3362399091f0a29550df3505b6a
Base64: fQ==

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/deterministic/leak-c2b7df6201fdd3362399091f0a29550df3505b6a

Output of `std::fmt::Debug`:

	ConfiguredModule {
	    config: NoImportsConfig,
	    valtypes: [
	        I32,
	        I64,
	        F32,
	        F64,
	    ],
	    outers: [],
	    initial_sections: [
	        Type(
	            [
	                Func(
	                    FuncType {
	                        params: [],
	                        results: [],
	                    },
	                ),
	            ],
	        ),
	    ],
	    import_names: {},
	    implicit_instance_types: {},
	    types: [
	        Defined {
	            section: 0,
	            nth: 0,
	        },
	    ],
	    func_types: [
	        0,
	    ],
	    module_types: [],
	    instance_types: [],
	    num_imports: 0,
	    num_aliases: 0,
	    num_defined_funcs: 0,
	    num_defined_tables: 0,
	    num_defined_memories: 0,
	    defined_globals: [],
	    funcs: [],
	    tables: [],
	    globals: [],
	    memories: [],
	    instances: [],
	    modules: [],
	    exports: [],
	    start: None,
	    elems: [],
	    code: [],
	    data: [],
	    type_size: 0,
	}

Reproduce with:

	cargo fuzz run deterministic fuzz/artifacts/deterministic/leak-c2b7df6201fdd3362399091f0a29550df3505b6a

Minimize test case with:

	cargo fuzz tmin deterministic fuzz/artifacts/deterministic/leak-c2b7df6201fdd3362399091f0a29550df3505b6a

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit code: 77
```

**Comment by Amanieu** [comment]
Superseded by #2692

**Pull request closed without merging**
