### PR TITLE
chore: Do not try to copy libwasmer_c_api.so if it does not exist

### PR DESCRIPTION
**Pull request by jubianchi**
This will help resolving wasmerio/wasmer-nightly#9 and #2003

### CODE REVIEW

**Review by MarkMcCaskey — APPROVED** [review]
Looks good to me assuming you tested it locally!

Makefiles are weird about shell and it wouldn't surprise me if this change breaks something

**Comment by syrusakbary** [comment]
Will the .so still be included in the distribution artifact for general Linux?

**Comment by jubianchi** [comment]
@syrusakbary yes it will: if the `.so` is here, it will be packaged, if it's not, only the `.a` will be packaged.

**Comment by jubianchi** [comment]
bors try

**Review by Hywan — APPROVED** [review]

**Pull request merged**
