### PR TITLE
Interrupt signal propagation

### PR DESCRIPTION
**Pull request by hanjukim**
# Description
If we embed wasmer to a process, wasmer will override interrupt(SIGINT) signal handler. In result, previous signal handler will not be called when SIGINT is fired, and if it gets fired again, process will be stopped by process::abort() which leads to output a long stack trace.

Related Issue: https://github.com/wasmerio/wasmer/issues/842

# Review
- [x] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by hanjukim** [comment]
@Hywan Can you review this? This change is essential to shutdown process gracefully.

**Comment by syrusakbary** [comment]
Hi @hanjukim we are in the mid of the process of upgrading Wasmer, that's why we are a bit slower replying here.

We will be super happy to invite you to it so you can try the new Wasmer, would you mind joining our slack channel so I can follow up there and make sure the issue is fixed? https://slack.wasmer.io/ Thanks! 🤗

**Comment by Hywan** [comment]
@hanjukim Sorry for the late reply. As @syrusakbary told you, a new version of Wasmer is coming, and your issue is likely to be resolved already. If you accept the invitation, you can try to replicate your issue. Thoughts?

**Comment by hanjukim** [comment]
> @hanjukim Sorry for the late reply. As @syrusakbary told you, a new version of Wasmer is coming, and your issue is likely to be resolved already. If you accept the invitation, you can try to replicate your issue. Thoughts?

@syrusakbary I justed joined to wasmer slack. Which branch should I use for testing new version candidate? Thanka for your help.

**Comment by hanjukim** [comment]
Ok. I reviewd new Wasmer (wasmer-reborn) and it seems a lot of things are changing. We are using cosmwasm which is a library that provides building cosmos-compatible wasm smart contracts and it is dependent on wasmer. Is there any chance that this PR could be merged to next release of (old) wasmer? If not, we will have to decide to fork every dependent repositories for our software release.

**Comment by syrusakbary** [comment]
> I reviewd new Wasmer (wasmer-reborn) and it seems a lot of things are changing

That's right. Thanks though for taking a sneak peek of the project!

> Is there any chance that this PR could be merged to next release of (old) wasmer?

Yeah, I think we can do that to facilitate your work!

**Comment by nlewycky** [comment]
While reviewing this PR, I began to wonder why we were installing a hander for SIGINT at all, and discovered that it's tied to the `managed` cfg feature. I moved the relevant code to be conditional under that feature, so we no longer install any handler for SIGINT by default. https://github.com/wasmerio/wasmer/pull/1552/

If you'd like to update this PR so that you can use `managed` and install your own signal handler for sigint, please rebase on top of the `0.x` branch. Thanks!

**Comment by syrusakbary** [comment]
This PR was done for the old codebase, which as commented by Nick it's also solved in `master`. Closing PR.

PS: thanks anyway for the contribution @hanjukim !

**Pull request closed without merging**
