### PR TITLE
Module.deserialize - accept AsEngineRef

### PR DESCRIPTION
**Pull request by dsherret**
I need this in order to use this code https://github.com/wasmerio/wasmer/pull/3378#issuecomment-1327679422 with `Module::deserialize` instead.

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
Thanks @dsherret, the CI error seems unrelated to your changes.
But could be possible to update also the `wasmer-cache` crate to use as well the `AsEngineRef`? Thanks!

**Comment by dsherret** [comment]
@syrusakbary I looked into it just now. It would require updating the `Cache` trait, which would be a breaking change. Is that ok?

**Comment by syrusakbary** [comment]
> It would require updating the Cache trait, which would be a breaking change. Is that ok?

Yes, that should be ok @dsherret. Thanks for double checking though!

**Comment by dsherret** [comment]
Should be good now.

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
Looks good. We have some issue in master that prevented tests to pass.
I updated the branch but tests should be passing soon!

**Comment by syrusakbary** [comment]
Still failing but it's independent on this PR

**Comment by theduke** [comment]
@syrusakbary 

Note: this breaks existing code.

Concretely, a value with type `&impl AsStoreRef` is not acceptect anymore.

(this is on the `wasix` branch)
```
error[E0277]: the trait bound `impl AsStoreRef: AsEngineRef` is not satisfied
   --> lib/wasi/src/bin_factory/module_cache.rs:201:39
    |
201 |                 let module = unsafe { Module::deserialize(store, &module_bytes[..]).unwrap() };
    |                                       ^^^^^^^^^^^^^^^^^^^ the trait `AsEngineRef` is not implemented for `impl AsStoreRef`
    |
note: required by a bound in `wasmer::Module::deserialize`
   --> /home/theduke/dev/github.com/wasmerio/wasmer/lib/api/src/sys/module.rs:270:23
    |
270 |         engine: &impl AsEngineRef,
    |                       ^^^^^^^^^^^ required by this bound in `wasmer::Module::deserialize`
help: consider further restricting this bound
    |
163 |         store: &impl AsStoreRef + wasmer::AsEngineRef,
    |                                 +++++++++++++++++++++
```

**Pull request merged**
