### PR TITLE
Fix unused import warnings during build

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by syrusakbary** [comment]
We are waiting on a refactor from @lachlansneff, so let's keep this PR open until the other refactor lands so there are no conflicts

**Comment by bjfish** [comment]
Closing cleaning up these imports for now ... I'll come back to this later on.

**Comment by bjfish** [comment]
@syrusakbary I reopened this because I can merge/fix conflicts in the refactor branch if there are any.

**Comment by bjfish** [comment]
I'll do this in the branch.

**Pull request closed without merging**
