### PR TITLE
Attempt to simplify build on linux

### LINKED ISSUE #1928: Undefined reference to `wasmer_raise_trap` when using native runtime
Hi,

I have some wasm code that compiles and runs fine using llvm/jit but does not run with llvm/native. I get the following error.
```
thread 'main' panicked at 'Failed to compile wasm: Compile(Codegen("/tmp/wasmer_nativeLFymlg.so: undefined symbol: wasmer_raise_trap"))', src/main.rs:27:19
```

It looks like wasmer is not linking something correctly, or maybe I need to define these symbols?

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Work in progress

Resolves #1928 (if it works)

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by Hywan** [comment]
Closed in favor of #2475.

**Pull request closed without merging**
