### PR TITLE
Depend on enumset instead of wasmer_enumset

### PR DESCRIPTION
**Pull request by coolreader18**
I'm not sure what ramifications this will have for semver, but since it's still relatively close to the release maybe 1.0.2 could be published and 1.0.{0,1} could be yanked? Not sure.

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
The audit failed because of external reasons to this PR. Merging

**Comment by MarkMcCaskey** [comment]
Glad to hear it got fixed!

Yeah, so the transition to wasmer-enumset was technically a breaking change (though as far as we know, no one was affected), but because the version we had already shipped was effectively broken, we were fine shipping it without incrementing...

Going the other way though, I'm not sure what the best practice is. This is a pretty exceptional circumstance as far as I know.

Another option which doesn't break anything is to modify the `wasmer-enumset` crate to just export the real `enumset`... that could reduce _some_ breakage but it's effectively the same thing and probably not worth it.

I'll talk with the team about this today

**Comment by Hywan** [comment]
> though as far as we know, no one was affected

Except `wasmer-python` :-). I can manage dealing with the breakage though.

**Pull request merged**
