### PR TITLE
Release 3.0.2

### PR DESCRIPTION
**Pull request by fschutt**
[bot] Release wasmer version 3.0.2

### CODE REVIEW

**Review by syrusakbary — CHANGES_REQUESTED** [review]
Please keep the changelog diff minimal, not sure what happened but can't be merged this way

**Review by syrusakbary — APPROVED** [review]

**Comment by fschutt** [comment]
[bot] Checks have passed. Publishing to crates.io...

**Comment by fschutt** [comment]
[bot] Checks have passed. Publishing to crates.io...

**Comment by fschutt** [comment]
Error publishin packages to crates.io:

```rust
   Compiling wasmer-compiler-llvm v3.0.2 (/private/var/folders/65/2zzy98b16xz254jccxjzqb8w0000gn/T/tmpcekyaxoe/target/package/wasmer-compiler-llvm-3.0.2)
error[E0308]: mismatched types
   --> src/trampoline/wasm.rs:72:26
    |
72  |             .set_section(FUNCTION_SECTION);
    |              ----------- ^^^^^^^^^^^^^^^^ expected enum `Option`, found `&str`
    |              |
    |              arguments to this function are incorrect
    |
    = note:   expected enum `Option<&str>`
            found reference `&'static str`
note: associated function defined here
   --> /Users/fs/.cargo/registry/src/github.com-1ecc6299db9ec823/inkwell-0.1.0-beta.5/src/values/global_value.rs:222:12
    |
222 |     pub fn set_section(self, section: Option<&str>) {
    |            ^^^^^^^^^^^
help: try wrapping the expression in `Some`
    |
72  |             .set_section(Some(FUNCTION_SECTION));
    |                          +++++                +

error[E0308]: mismatched types
   --> src/trampoline/wasm.rs:192:26
    |
192 |             .set_section(FUNCTION_SECTION);
    |              ----------- ^^^^^^^^^^^^^^^^ expected enum `Option`, found `&str`
    |              |
    |              arguments to this function are incorrect
    |
    = note:   expected enum `Option<&str>`
            found reference `&'static str`
note: associated function defined here
   --> /Users/fs/.cargo/registry/src/github.com-1ecc6299db9ec823/inkwell-0.1.0-beta.5/src/values/global_value.rs:222:12
    |
222 |     pub fn set_section(self, section: Option<&str>) {
    |            ^^^^^^^^^^^
help: try wrapping the expression in `Some`
    |
192 |             .set_section(Some(FUNCTION_SECTION));
    |                          +++++                +

error[E0308]: mismatched types
   --> src/translator/code.rs:109:44
    |
109 |         func.as_global_value().set_section(FUNCTION_SECTION);
    |                                ----------- ^^^^^^^^^^^^^^^^ expected enum `Option`, found `&str`
    |                                |
    |                                arguments to this function are incorrect
    |
    = note:   expected enum `Option<&str>`
            found reference `&'static str`
note: associated function defined here
   --> /Users/fs/.cargo/registry/src/github.com-1ecc6299db9ec823/inkwell-0.1.0-beta.5/src/values/global_value.rs:222:12
    |
222 |     pub fn set_section(self, section: Option<&str>) {
    |            ^^^^^^^^^^^
help: try wrapping the expression in `Some`
    |
109 |         func.as_global_value().set_section(Some(FUNCTION_SECTION));
    |                                            +++++                +

error[E0614]: type `ContextRef<'_>` cannot be dereferenced
    --> src/translator/intrinsics.rs:1692:25
     |
1692 |         let context2 = &*context;
     |                         ^^^^^^^^

Some errors have detailed explanations: E0308, E0614.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `wasmer-compiler-llvm` due to 4 previous errors
error: failed to verify package tarball
    Updating crates.io index
   Packaging wasmer v3.0.2 (/private/var/folders/65/2zzy98b16xz254jccxjzqb8w0000gn/T/tmpcekyaxoe/lib/api)
   Verifying wasmer v3.0.2 (/private/var/folders/65/2zzy98b16xz254jccxjzqb8w0000gn/T/tmpcekyaxoe/lib/api)
error: failed to verify package tarball

```

**Comment by fschutt** [comment]
@syrusakbary `inkwell` released a new version with some breaking changes from `0.1.0-beta.4` to `0.1.0-beta.5`. As far as I can see, it's just wrapping things in `Some()` values, so I'll fix them here and wait for the tests to pass, then publish again.

This is exactly why I didn't want to merge immediately, and it's also why I once published wapm2pirita with local changes, sometimes issues can happen when cargo publishes thanks to automatic semver upgrades that don't happen in the CI.

**Comment by fschutt** [comment]
It seems that `cargo publish` does an automatic `cargo update` before publishing, which is why these errors happen at all.

We should put that in the CI, but it would potentially introduce unexpected CI breaks.

**Comment by fschutt** [comment]
[bot] Checks have passed. Publishing to crates.io...

**Comment by fschutt** [comment]
[bot] Successfully published wasmer version 3.0.2 to crates.io

**Pull request merged**
