### PR TITLE
Internal runtime ↔️ backend abstraction refactor.

### PR DESCRIPTION
**Pull request by lachlansneff**
This replaces the `ProtectedCaller` and `FuncResolver` traits with a combined `RunnableModule` trait. I'd like to get this merged, since it's standalone, but there are follow-up PRs I'd like to make that will further change the abstraction

### CODE REVIEW

**Comment by lachlansneff** [comment]
bors try

**Comment by syrusakbary** [comment]
bors try

**Comment by lachlansneff** [comment]
bors try

**Comment by lachlansneff** [comment]
thank you @bjfish 

bors r+

**Pull request merged**
