### PR TITLE
Cranelift: enable SIMD based on actual Wasm features

### PR DESCRIPTION
**Pull request by jubianchi**
# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Review by syrusakbary — APPROVED** [review]

**Comment by jubianchi** [comment]
bors try

**Review by MarkMcCaskey — CHANGES_REQUESTED** [review]
I messaged about this on Slack, but I don't think we want `Features::enable_simd` to be related to this other use of simd which is entirely unrelated as I understand it. If we want to control low-level compiler details with `Features`, I think we need to add new fields, ideally in a new sub-struct to keep things organized

**Review by MarkMcCaskey — APPROVED** [review]
I think the title is misleading now, but my previous objection seems to no longer be in the PR. I do think we need to be careful about separating the ideas of codegen simd from Wasm simd though

**Comment by jubianchi** [comment]
bors try

**Review by syrusakbary — APPROVED** [review]

**Pull request merged**
