### PR TITLE
Unify test running of compilers

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
The idea behind this PR is to spend less time compiling in CI and just run all of our tests in parallel directly.

There are still a couple of rough edges, but it works. It's higher priority to do this for the C API but here it is for our core tests. This should improve caching and the performance of our CI tests.

We still require 2 compilation steps rather than 1 for this part, but hopefully we can still see some of the benefits of this

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by MarkMcCaskey** [comment]
bors try

**Comment by syrusakbary** [comment]
I was thinking on having something similar, but via a macro that tests can be decorated.

So something like this:
```rust
#[test]
#[variadic_test(engine = ["jit", "native], compiler = ["singlepass", "cranelift", "llvm"])]
fn my_test(engine: &str, compiler: &str) {
}
```

Which will expand to something like:
```rust
mod my_test {
    use super::*;
    fn my_test(engine: &str, compiler: &str) {
    }
    mod jit {
        mod singlepass {
            #[test]
            fn test() {
                super::super::my_test("jit", "singlepass"); 
            }
            ...
        }
    }
    mod native {
        ...
    }
}
```

**Comment by MarkMcCaskey** [comment]
When I first saw that I didn't like it because macros complicate things, but I actually think that's a really good idea and would make this a lot cleaner

Would just need a way to opt out specific combinations of things like `engine+compiler`

**Comment by syrusakbary** [comment]
Similar to quickcheck, but with fixed values:
https://github.com/BurntSushi/quickcheck

PS: this is caused because Rust doesn't have a proper test framework :(
https://rust-lang.github.io/rfcs/2318-custom-test-frameworks.html

**Comment by MarkMcCaskey** [comment]
> PS: this is caused because Rust doesn't have a proper test framework :(

haha I'd probably call that a test framework framework, but I agree, that would be nice to have!

**Comment by syrusakbary** [comment]
Ok, someone might have already done most of the work for us!
https://altsysrq.github.io/proptest-book/proptest/tutorial/macro-proptest.html

**Comment by syrusakbary** [comment]
I think we can close this PR in favor of #2321

**Pull request closed without merging**
