### PR TITLE
fixing breaking change of `wasmparser`

### PR DESCRIPTION
**Pull request by YaronWittenstein**
Edit by @Hywan: Fix #707

### CODE REVIEW

**Comment by Hywan** [comment]
cc @xmclark @nlewycky, can you get a second review please? Do we want to update wasmparser now?

**Comment by Hywan** [comment]
bors try

**Comment by nlewycky** [comment]
I'm surprised it passed. The version of `wasmparser` used by wasmer and used by the cranelift crate used in wasmer must match or there should be a build failure.

If it builds, that's great though?

**Comment by YaronWittenstein** [comment]
> I'm surprised it passed. The version of `wasmparser` used by wasmer and used by the cranelift crate used in wasmer must match or there should be a build failure.
> 
> If it builds, that's great though?

_Bors_ failed above because of the duplicate `wasmerparser` versions

**Pull request closed without merging**
