### PR TITLE
Feature/singlepass windows

### PR DESCRIPTION
**Pull request by ptitSeb**
# Description

Added Windows x86_64 support to SinglePass Compiler.

Compared to System V ABI, the Windows ABI changed the way argument are send to function in the following way:
1. Only the 4 1st arguments can be send in register.
2. The argument will go in XMM reg is Float or Double, or in GPR for anything else
3. Regs are RCX/XMM0, RDX/XMM1, R8/XMM2 and R9/XMM3
4. Other argument go to the stack
5. There is 32bytes also reserved in the stack to shadow the 4 arguments if the callee function needs too

### CODE REVIEW

**Review by syrusakbary — COMMENTED** [review]
Right now we are using compilation flags `#[cfg(target_os = "windows")]` to determine the output.

To allow cross-compilation it would be great to have it depending on a runtime flag (we can add the `compiler::Target` to the `Singlepass` struct, and check the target OS there)

**Comment by ptitSeb** [comment]
bors try

**Comment by ptitSeb** [comment]
bors try

**Comment by ptitSeb** [comment]
bors try

**Comment by ptitSeb** [comment]
bors try

**Comment by ptitSeb** [comment]
bors try

**Pull request merged**
