### PR TITLE
bors.toml: add checks

### PR DESCRIPTION
**Pull request by epilys**

### CODE REVIEW

**Comment by ptitSeb** [comment]
This was removed from bors on purpose, because testing was already done before the r+ command was done

**Comment by epilys** [comment]
Yeah but I noticed yesterday it'd still merge a PR even if the testing wasn't finished.

**Comment by epilys** [comment]
Bah, this will fail since this commit doesn't change any part of the code hence all the other tests won't run hence bors will timeout waiting on the code tests to be run... what a mess. I'll just close the PR and give up.

**Pull request closed without merging**
