### PR TITLE
Integrate with Fuzzit

### PR DESCRIPTION
**Pull request by bookmoons**
# Description

Enables automated fuzzing on Fuzzit. Fuzz regression tests run every push and PR. Full fuzzing runs every push.

Uses the existing fuzz targets:
* simple-instantiate - Instantiate a WebAssembly program.
* validate-wasm - Validate WebAssembly code.
* compile-wasm - Compile WebAssembly code.

# Review

- [x] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by bookmoons** [comment]
Refreshing #727 which ran into a build problem. This patch also updates to use the latest Fuzzit client.

Corrected instructions for handling credentials:
* In [Fuzzit](https://fuzzit.dev/) use the dropdown to switch to the wasmer org.
* In settings grab an API key.
* In Azure Pipelines, Edit the pipeline, open Variables, and paste the key to a FUZZIT_API_KEY variable. Make it secret to prevent exposure.

**Comment by syrusakbary** [comment]
Great, can you add a short description in the Changelog as well? https://github.com/wasmerio/wasmer/blob/master/CHANGELOG.md

Thanks!

**Comment by bookmoons** [comment]
Updated that changelog, and got it rebased onto the latest.

**Comment by bookmoons** [comment]
Looks like there was another change already. You guys move fast. Rebased again.

**Comment by bookmoons** [comment]
I see in the build log there was a permission failure:
https://dev.azure.com/wasmerio/wasmer/_build/results?buildId=1252

Were you able to get at the API key in fuzzit?

**Comment by syrusakbary** [comment]
Closing PR as is stale with new codebase.

**Pull request closed without merging**
