### PR TITLE
feat(runtime-core) Nicer panic output

### PR DESCRIPTION
**Pull request by lachlansneff**
This adds the human-panic crate to print out a nicer panic message (as well as log the backtrace and whatnot).

Example output:

```
Well, this is embarrassing.

The Wasmer Runtime had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/24/mfj_dsx13ln7jxrnrbb2vq0h0000gn/T/report-5012e1cd-3834-4ff2-8e3f-5b42c5735ca3.toml". Submit an issue or email with the subject of "The Wasmer Runtime Crash Report" and include the report as an attachment.

- Homepage: https://github.com/wasmerio/wasmer
- Authors: Wasmer Engineering <engineering@wasmer.io>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

### CODE REVIEW

**Comment by lachlansneff** [comment]
bors try

**Comment by syrusakbary** [comment]
Actually, I created an account on Sentry. It might be a good idea to send the error there as well? (and remove the "automated error collection" phrase :P )

**Comment by lachlansneff** [comment]
I don't think we should automatically log the errors. It seems too much like telemetry. We can probably add stuff about submitting a report on sentry though.

**Comment by lachlansneff** [comment]
bors try

**Comment by CryZe** [comment]
Shouldn't this be behind a feature gate? This is great for wasmer, but not so great for other applications using wasmer as a dependency.

**Comment by lachlansneff** [comment]
@CryZe Yeah, it seems like having this installed by default is a bad idea. Also, it doesn't always get installed (depends on the type of crate that depends on the runtime). I'll install this in the wasmer cli app, and let users do install it from the runtime if they want.

**Comment by syrusakbary** [comment]
Closing the PR, as is stale.
We will re-do it when becomes a priority again

**Pull request closed without merging**
