### PR TITLE
Fix warnings on windows build

### PR DESCRIPTION
**Pull request by xmclark**
Another developer recently went through and fixed many warnings that were polluting the build:

https://github.com/wasmerio/wasmer/pull/265
https://github.com/wasmerio/wasmer/pull/264
https://github.com/wasmerio/wasmer/pull/263
https://github.com/wasmerio/wasmer/pull/266

This was super great 💟 and it encouraged me to do the same. 

This PR addresses warnings emitted on the windows build. Many warnings from the emscripten and clif-backend module are fixed.

### CODE REVIEW

**Comment by xmclark** [comment]
bors try

**Comment by xmclark** [comment]
The remaining warnings are odd ones. From the latest appveyor build:
```
warning: `extern` block uses type `()` which is not FFI-safe: tuples have unspecified layout
  --> lib\win-exception-handler\src\exception_handling.rs:17:21
   |
17 |         trampoline: Trampoline,
   |                     ^^^^^^^^^^
   |
   = note: #[warn(improper_ctypes)] on by default
   = help: consider using a struct instead
warning: `extern` block uses type `()` which is not FFI-safe: tuples have unspecified layout
  --> lib\win-exception-handler\src\exception_handling.rs:18:14
   |
18 |         ctx: *mut Ctx,
   |              ^^^^^^^^
   |
   = help: consider using a struct instead
 ```

**Comment by Hywan** [comment]
Thanks 🙇!

**Pull request merged**
