### PR TITLE
Fix up readme files, remove version numbers

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
[rendered](https://github.com/wasmerio/wasmer/blob/fix/readme-outdated-version-numbers/lib/api/README.md)

# Review

- [ ] Add a short description of the the change to the CHANGELOG.md file

### CODE REVIEW

**Review by Hywan — APPROVED** [review]
Looks good to me!

**Comment by sakar20110** [comment]
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

**Review by ioan555 — COMMENTED** [review]
Па

**Pull request merged**
