### PR TITLE
Remove FuncRef registry - WIP

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Intermediate fix for funcref lifetimes:

- [ ] Disable public APIs for funcrefs
- [ ] Scope funcref backing to the Instance itself
- [ ] In the future use reference counting to make things work fully

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
Tests are failing, running here to show what is failing:

bors try

**Comment by freesig** [comment]
I'm not sure if this is helpful but I'm seeing very high cpu usage in our application when using wasmer 2.0 and I did a flamegraph. It seems like there is a lock in the `FuncDataRegistry::register` that is getting hit a lot (about 60% of the cpu usage).
Screen Shot 2021-06-24 at 10 01 30 am

**Comment by syrusakbary** [comment]
Thanks for the report @freesig

**Comment by MarkMcCaskey** [comment]
@freesig Thanks! That is very useful to know. Can you provide some more info about your usage pattern? Are you instantiating modules on multiple threads?

This PR should fix that because it removes the lock and FuncDataRegistry

**Comment by freesig** [comment]
Yep definitely instantiating on different threads

**Comment by Amanieu** [comment]
Closing in favor of #2699

**Pull request closed without merging**
