### PR TITLE
fix popcnt for aarch64

### PR DESCRIPTION
**Pull request by grishasobol**
# Description
Fix problem with infinite `popcnt` WASM instruction execution on M1 processor. See details in corresponded issue: https://github.com/wasmerio/wasmer/issues/3210

# Review
1) Make fix for `i32.popcnt`. Use additional execution branch if `src` register equal to `1`:
```
if src == 0 => goto exit_label
if src == 1 => goto src_is_one_label

loop_label:
... // popcnt loop body

goto exit_label

src_is_one_label:
mov dest, 1

exit_label:
```

### CODE REVIEW

**Comment by ptitSeb** [comment]
Thank you for the bug report, the detailled analysis, and the PR :)

I have checked ARM64 documentation, and in fact, the LSL will behave like you describe on all Aarch64 platform, not only M1 cpu, so you can remove the Apple specific compile tag.
The doc list:
```
result = ShiftReg(n, shift_type, UInt(operand2) MOD datasize);
```
so we see the modulo datasize for the shift value.


As for the fix, I would prefer some more simple, like changing
```rust
        self.assembler.emit_clz(Size::S32, src, tmp)?; // clz src => tmp
        self.assembler
            .emit_add(Size::S32, tmp, Location::Imm8(1), tmp)?; // inc tmp
        self.assembler.emit_lsl(Size::S32, src, tmp, src)?; // src << tmp => src
        self.assembler.emit_cbnz_label(Size::S32, src, label_loop)?; // if src!=0 goto loop
```
to
```rust
        self.assembler.emit_clz(Size::S32, src, tmp)?; // clz src => tmp
        self.assembler.emit_lsl(Size::S32, src, tmp, src)?; // src << tmp => src
        self.assembler.emit_lsl(Size::S32, src, Location::Imm8(1), src)?; // src << 1 => src
        self.assembler.emit_cbnz_label(Size::S32, src, label_loop)?; // if src!=0 goto loop
```
for the 32bits popcnt, to workaround the 31+1=32 issue.

I tested this with your test on a aarhc64/linux box, and the change is both needed and working.

**Comment by grishasobol** [comment]
Sure)) your solution is much better. Will do it

**Review by ptitSeb — APPROVED** [review]

**Comment by ptitSeb** [comment]
@grishasobol can you please run `cargo fmt --all` and push the diff, the lint is failing, sorry.

**Review by ptitSeb — APPROVED** [review]

**Pull request merged**
