### PR TITLE
chore(compiler) Remove `ModuleInfoTranslate`

### PR DESCRIPTION
**Pull request by syrusakbary**
# Description

After #2460, I realized there can be some code that is simplified.

# Review

- [ ] Add a short description of the change to the CHANGELOG.md file

### CODE REVIEW

**Review by Hywan — COMMENTED** [review]
Thanks for the PR.

It removes `ModuleInfoTranslation` and updates the code accordingly. Can you justify why `ModuleInfoTranslate` is no longer required please :-)?

**Comment by Hywan** [comment]
And please, update the `CHANGELOG`.

**Comment by syrusakbary** [comment]
> Can you justify why ModuleInfoTranslate is no longer required please :-)?

`ModuleInfoTranslate` is an abstraction that is unnecessary and not used anywhere outside of the crate.
It was only necessary because an extra field is not really needed at all. This PR simplifies the code

**Review by Hywan — APPROVED** [review]
bors r+

**Pull request merged**
