### PR TITLE
Fix calculation of stat.st_size in the presence of combined seeks and writes

### PR DESCRIPTION
**Pull request by Arshia001**

### CODE REVIEW

**Review by maminrayej — COMMENTED** [review]
Looks reasonable to me. But for this PR to be more inline with other recent fixes to wasix and virtual-fs, I'd like to see a wasi-fyi test that fails before this PR and passes after, so we know this fixes the issue and prevents any future regressions of this sort.

**Comment by Arshia001** [comment]
@maminrayej technically, `wasi-fyi` tests weren't created by us, so we should put the test somewhere else I believe.

**Comment by syrusakbary** [comment]
@Arshia001 we can add them in wasi-fyi for now and open PRs later, that's ok!

**Comment by Arshia001** [comment]
@syrusakbary @maminrayej I added the test, can you please re-review and approve?

**Review by maminrayej — APPROVED** [review]

**Pull request merged**
